/**
 * The API surface report gate.
 *
 * `.api.md` is a committed snapshot of every package's public TypeScript surface. CI regenerates it
 * and fails on any diff, so a signature cannot change without the change being visible in review.
 * Publishing is a one-way door; this is the file that makes the door visible.
 *
 * Generated by `@microsoft/api-extractor` rather than by parsing `.d.ts` here. That is a deliberate
 * dependency: this project has now hand-rolled parsing four times - glob semantics twice, a CSS
 * selector reader, and a "rules outside a layer" check - and got it wrong every time. Type
 * extraction is strictly harder than any of those.
 *
 * Also enforces D0003 / TRD ADR-004: no Radix type may reach the public surface. `asChild`,
 * `onOpenChange` and `data-state` are never Clara API, and a leaked Radix TYPE would drag its whole
 * idiom into the contract permanently.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { fail, pass, readWorkspace } from './lib/workspace.mjs'

const root = process.cwd()
const local = process.argv.includes('--local')
const problems = []
const reports = []

for (const { dir, kind, manifest } of readWorkspace(root)) {
  if (kind !== 'packages' || manifest.private) continue
  const config = join(root, dir, 'api-extractor.json')
  if (!existsSync(config)) {
    problems.push(`${manifest.name}: no api-extractor.json - its public surface is unreported`)
    continue
  }
  if (!existsSync(join(root, dir, 'dist/index.d.ts'))) {
    problems.push(`${manifest.name}: no dist/index.d.ts - build before running the API gate`)
    continue
  }

  try {
    execFileSync('npx', ['api-extractor', 'run', ...(local ? ['--local'] : []), '--config', config], {
      cwd: root,
      stdio: 'pipe',
      encoding: 'utf8',
    })
  } catch (error) {
    const out = String(error.stdout ?? '') + String(error.stderr ?? '')
    // The report differing from the committed one is the gate firing, not a tool failure. The
    // previous pattern was /The API report is not up to date/, which api-extractor never emits -
    // the branch was dead, so a real surface change reported as a generic tool failure and the
    // "run pnpm api:update" advice was unreachable (review H7). Matched against what it actually
    // prints, with the older wording kept as an alternative.
    const diff = out.match(/You have changed the API signature[^\n]*/) ??
      out.match(/The API report is not up to date[^\n]*/)
    problems.push(
      diff
        ? `${manifest.name}: ${diff[0]} Run \`pnpm api:update\` and commit the change - a public ` +
            'signature moved, and that must be visible in review.'
        : `${manifest.name}: api-extractor failed - ${out.split('\n').filter(Boolean).slice(-2).join(' ').slice(0, 160)}`,
    )
    continue
  }

  const shortName = manifest.name.replace('@luzentialabs/', '')
  const reportPath = join(root, dir, `etc/${shortName}.api.md`)
  if (!existsSync(reportPath)) {
    problems.push(`${manifest.name}: report missing at ${reportPath.slice(root.length + 1)}`)
    continue
  }
  reports.push(shortName)

  // The public surface contract (AGENTS.md "Code style", D0003, TRD ADR-004). A `@radix-ui` grep
  // alone passed a surface declaring `asChild`, `onOpenChange`, `sneaky: any` and `variant: string`
  // all at once (review H8) - every one of those is permanent once published, and neither of the
  // gates nominally covering them can see them: `tsc` cannot flag an explicit `any`, and the lint
  // gate is still pending.
  const report = readFileSync(reportPath, 'utf8')
  // Comments carry prose that would false-positive on every rule below.
  const surface = report.split('\n').filter((l) => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n')

  if (/@radix-ui/.test(surface)) {
    const lines = surface.split('\n').filter((l) => l.includes('@radix-ui')).slice(0, 3)
    problems.push(
      `${manifest.name}: a Radix type reaches the public surface (D0003, TRD ADR-004): ` +
        `${lines.join(' | ')}. Radix is an implementation detail; \`as\` is Clara's single ` +
        'polymorphism idiom, and a leaked Radix type makes its whole contract permanent.',
    )
  }

  // Radix prop names are never Clara API, however they got there.
  for (const prop of ['asChild', 'onOpenChange', 'data-state']) {
    const hit = surface.split('\n').find((l) => new RegExp(`\\b${prop.replace('-', '\\-')}\\b`).test(l))
    if (hit) {
      problems.push(
        `${manifest.name}: \`${prop}\` is in the public surface - it is Radix's API, never Clara's ` +
          `(AGENTS.md, Section 4 rules 7-8): ${hit.trim().slice(0, 100)}`,
      )
    }
  }

  // No `any` in a public signature. This is gate 1's stated contract, and `tsc --noEmit` cannot
  // enforce it - an explicit `any` is valid TypeScript.
  for (const line of surface.split('\n')) {
    if (/(?::|<|,|\()\s*any\b/.test(line) && !/\bas any\b/.test(line)) {
      problems.push(
        `${manifest.name}: \`any\` in a public signature (AGENTS.md): ${line.trim().slice(0, 100)}`,
      )
      break
    }
  }

  // Prop types use literal unions, never bare `string`, wherever the value set is closed. Reported
  // for a named review decision rather than auto-failed: an open-ended string prop is legitimate
  // (a label, an id), so this names the line and asks for the union or an explicit exemption.
  for (const line of surface.split('\n')) {
    if (/\b(variant|size|tone|intent|density|align|justify|direction|status|placement)\??:\s*string\b/.test(line)) {
      problems.push(
        `${manifest.name}: a closed-set prop is typed as bare \`string\` (AGENTS.md): ` +
          `${line.trim().slice(0, 100)} - use a literal union; widening later is fine, narrowing is breaking.`,
      )
    }
  }
}

if (problems.length) fail('api-report', problems)
pass('api-report', `${reports.length} public surface report(s) current [${reports.join(', ')}], no Radix leak, no forbidden prop, no \`any\`, no bare-string closed-set prop`)
