/**
 * The API surface report gate.
 *
 * `.api.md` is a committed snapshot of every package's public TypeScript surface. CI regenerates it
 * and fails on any diff, so a signature cannot change without the change being visible in review.
 * Publishing is a one-way door; this is the file that makes the door visible.
 *
 * Generated by `@microsoft/api-extractor` rather than by parsing `.d.ts` here. That is a deliberate
 * dependency: this project has now hand-rolled parsing four times - glob semantics twice, a CSS
 * selector reader, and a "rules outside a layer" check - and got it wrong every time. Type
 * extraction is strictly harder than any of those.
 *
 * Also enforces D0003 / TRD ADR-004: no Radix type may reach the public surface. `asChild`,
 * `onOpenChange` and `data-state` are never Clara API, and a leaked Radix TYPE would drag its whole
 * idiom into the contract permanently.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { fail, pass, readWorkspace } from './lib/workspace.mjs'
import { checkSurface } from './lib/surface-contract.mjs'

const root = process.cwd()
const local = process.argv.includes('--local')
const problems = []
const reports = []

for (const { dir, kind, manifest } of readWorkspace(root)) {
  if (kind !== 'packages' || manifest.private) continue
  const config = join(root, dir, 'api-extractor.json')
  if (!existsSync(config)) {
    problems.push(`${manifest.name}: no api-extractor.json - its public surface is unreported`)
    continue
  }
  if (!existsSync(join(root, dir, 'dist/index.d.ts'))) {
    problems.push(`${manifest.name}: no dist/index.d.ts - build before running the API gate`)
    continue
  }

  try {
    execFileSync('npx', ['api-extractor', 'run', ...(local ? ['--local'] : []), '--config', config], {
      cwd: root,
      stdio: 'pipe',
      encoding: 'utf8',
    })
  } catch (error) {
    const out = String(error.stdout ?? '') + String(error.stderr ?? '')
    // The report differing from the committed one is the gate firing, not a tool failure. The
    // previous pattern was /The API report is not up to date/, which api-extractor never emits -
    // the branch was dead, so a real surface change reported as a generic tool failure and the
    // "run pnpm api:update" advice was unreachable (review H7). Matched against what it actually
    // prints, with the older wording kept as an alternative.
    const diff = out.match(/You have changed the API signature[^\n]*/) ??
      out.match(/The API report is not up to date[^\n]*/)
    problems.push(
      diff
        ? `${manifest.name}: ${diff[0]} Run \`pnpm api:update\` and commit the change - a public ` +
            'signature moved, and that must be visible in review.'
        : `${manifest.name}: api-extractor failed - ${out.split('\n').filter(Boolean).slice(-2).join(' ').slice(0, 160)}`,
    )
    continue
  }

  const shortName = manifest.name.replace('@luzentialabs/', '')
  const reportPath = join(root, dir, `etc/${shortName}.api.md`)
  if (!existsSync(reportPath)) {
    problems.push(`${manifest.name}: report missing at ${reportPath.slice(root.length + 1)}`)
    continue
  }
  reports.push(shortName)

  // The public surface contract lives in lib/surface-contract.mjs, pure and unit-tested. Inline
  // here the rules could only be exercised by editing a real .api.md, which api-extractor's drift
  // check rejects first - so they were never actually proven to fire.
  problems.push(...checkSurface(manifest.name, readFileSync(reportPath, 'utf8')))
}

if (problems.length) fail('api-report', problems)
pass('api-report', `${reports.length} public surface report(s) current [${reports.join(', ')}], no Radix leak, no forbidden prop, no \`any\`, no bare-string closed-set prop`)
