#!/usr/bin/env node
/**
 * Generate the React icon components and ICONS.md from the SVG sources.
 *
 * The list is GENERATED from the same source the components are, so `ICONS.md` cannot drift from
 * what ships - which is the failure PRD:357 is written against ("at minimum the icons we need" is
 * not a list, and CI cannot check it). `check-icons.mjs` then verifies the three agree: the source
 * files, the exports, and the committed list.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const catalogue = JSON.parse(readFileSync(join(here, 'icons.json'), 'utf8'))
const pascal = (name) => name.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('')

const src = join(here, 'src')
mkdirSync(join(src, 'icons'), { recursive: true })

const all = []
for (const [category, icons] of Object.entries(catalogue.categories)) {
  for (const name of Object.keys(icons)) {
    const file = join(here, 'svg', `${name}.svg`)
    const body = readFileSync(file, 'utf8').match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1]?.trim()
    if (!body) throw new Error(`${name}.svg has no drawable content`)
    const component = `${pascal(name)}Icon`
    all.push({ name, component, category })
    writeFileSync(join(src, 'icons', `${component}.tsx`),
      `// GENERATED from svg/${name}.svg by generate-icons.mjs. Do not edit.\n` +
      `import { Icon, type IconProps } from '../Icon'\n\n` +
      `export function ${component} (props: IconProps) {\n` +
      `  return <Icon {...props}>${body}</Icon>\n}\n`)
  }
}

writeFileSync(join(src, 'generated.ts'),
  '// GENERATED by generate-icons.mjs. Do not edit.\n' +
  all.map((i) => `export { ${i.component} } from './icons/${i.component}'`).join('\n') + '\n')

const rows = Object.entries(catalogue.categories).map(([category, icons]) => {
  const names = Object.keys(icons).sort()
  return `### ${category} (${names.length})\n\n` +
    names.map((n) => `- \`${pascal(n)}Icon\` (\`${n}.svg\`)`).join('\n')
}).join('\n\n')

writeFileSync(join(here, 'ICONS.md'),
`# The v1 icon set

**${all.length} icons.** GENERATED from \`icons.json\` and \`svg/\` - do not edit by hand.

PRD:357 requires this to be an enumerated, counted list committed before implementation, rather
than "at minimum the icons we need". A list nobody can count is one CI cannot check, so
\`check-icons.mjs\` fails when an exported icon is absent here, when a listed icon is unexported,
or when a category's count moves.

Every icon is drawn on a 24x24 grid with a 2px stroke and round caps. They are read at 16-20px in
dense toolbars, where detail becomes noise, so the geometry is deliberately plain.

## Using them

Icons are **decorative by default** and hidden from assistive technology. An icon that carries
meaning on its own takes a \`label\`, which becomes its accessible name:

\`\`\`tsx
<TrashIcon />                       // decorative, beside a text label
<DeleteIcon label="Delete row" />   // meaningful on its own
\`\`\`

They inherit \`currentColor\` and size from their context, so they take the colour of the text
around them without a prop.

${rows}
`)
console.log(`PASS [icons] ${all.length} icon(s) generated across ${Object.keys(catalogue.categories).length} categories`)
